// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "Title.Wishlists": "Wishlists",
  "Title.WishlistCreate": "Crete a new list",
  "Title.WishlistItemAdd": "Add item",
  "Title.WishlistsShared": "Shared wishlists",
  "Menu.Wishlists": "Wishlists",
  "Menu.Profile": "Me",
  "Action.CreateWishlist": "Create Wishlist",
  "Wishlists.Empty": "You don't have wishlists yet",
  "Item.Empty": "Что-то пошло не так...",
  "Action.SaveWishlist": "Save",
  "Form.Wishlist.Date": "Event date",
  "Form.Wishlist.Date.Placeholder": "Select Date",
  "Form.Wishlist.Title": "Wishlist title",
  "Form.Wishlist.Title.Placeholder": "Untitled",
  "Form.Wishlist.Description": "Description",
  "Form.Wishlist.Description.Placeholder": "Optional",
  "Action.AddItem": "Add Item",
  "Form.AddItem.Url": "URL",
  "Form.AddItem.Url.Placeholder": "example.com",
  "Form.AddItem.Name": "Title",
  "Action.BookItem": "Book Item",
  "Action.UnbookItem": "Cancel Book",
  "Share.Title": "Share link with your friends",
  "Share.Copy": "Copy link",
  "Share.Telegram": "Share in Telegram",
  "Share.Wishlist.Text": "Sharing my wishlist {name}",
  "Shared.Title": "Shared with you",
  "Shared.Action.View": "View",
}
