// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "Title.Wishlists": "Wishlists",
  "Title.WishlistCreate": "Crete a new list",
  "Title.WishlistItemAdd": "Add item",
  "Title.WishlistsShared": "Shared wishlists",
  "Menu.Wishlists": "Wishlists",
  "Menu.Profile": "Me",
  "Action.CreateWishlist": "Create Wishlist",
  "Wishlists.Empty": "You don't have wishlists yet",
  "Action.SaveWishlist": "Save",
  "Form.Wishlist.Title": "Wishlist title",
  "Form.Wishlist.Title.Placeholder": "Untitled",
  "Form.Wishlist.Description": "Description",
  "Form.Wishlist.Description.Placeholder": "Optional",
  "Action.AddItem": "Add Item",
  "Form.AddItem.Url": "URL",
  "Form.AddItem.Url.Placeholder": "example.com",
  "Form.AddItem.Name": "Title",
}
