// eslint-disable-next-line import/no-anonymous-default-export
export default {
  "Title.Wishlists": "Вишлисты",
  "Title.WishlistCreate": "Создание вишлиста",
  "Title.WishlistItemAdd": "Добавление подарка",
  "Title.WishlistsShared": "Вишлисты друзей",
  "Menu.Wishlists": "Вишлисты",
  "Menu.Profile": "Профиль",
  "Action.CreateWishlist": "Создать Вишлист",
  "Wishlists.Empty": "У вас пока нет вишлистов",
  "Item.Empty": "Something went wrong...",
  "Action.SaveWishlist": "Сохранить",
  "Form.Wishlist.Date": "Дата события",
  "Form.Wishlist.Date.Placeholder": "Выберите дату",
  "Form.Wishlist.Title": "Название вишлиста",
  "Form.Wishlist.Title.Placeholder": "Без названия",
  "Form.Wishlist.Description": "Описание",
  "Form.Wishlist.Description.Placeholder": "Опционально",
  "Action.AddItem": "Добавить",
  "Form.AddItem.Url": "URL",
  "Form.AddItem.Url.Placeholder": "example.com",
  "Form.AddItem.Name": "Название",
  "Action.BookItem": "Забронировать",
  "Action.UnbookItem": "Отменить Бронь",
  "Share.Title": "Поделитесь ссылкой с друзьями",
  "Share.Copy": "Копировать ссылку",
  "Share.Telegram": "Поделиться в Telegram",
  "Share.Wishlist.Text": "Делюсь своим вишлистом {name}",
  "Shared.Title": "C вами поделились",
  "Shared.Action.View": "Просмотр",
}
